version: '3'
services:
  blog-service:
    build: ./api-blog
    ports: 
      - "5000:5000"
    container_name: blog-service
    restart: always
    environment:
      - DB_HOST=mongodb://mongo:27017
      - DB_NAME=blog
      - PORT=5000
      - JWT_SECRET_KEY=Blog_2019
      - ALLOW_ORIGIN=*
      - ELASTIC_HOST=6fe9844970424bf4b956708763171ef5.us-east-1.aws.found.io
      - ELASTIC_PORT=9243
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=rcuKCjRHpKZHERJcsq0cgd0W
    networks:
      - blog-network
  web:
    build: ./web
    ports: 
      - "5001:5001"
    container_name: web
    restart: always
    environment:
      - API_ENDPOINT=http://localhost:5000/api
    networks:
      - blog-network
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
